import { network } from "hardhat";
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";

async function main() {
    const { ethers } = (await network.connect()) as any;

    const verifier = await ethers.deployContract("Groth16Verifier");
    const verifierAddr = await verifier.getAddress();
    console.log("Groth16Verifier:", verifierAddr);

    const registry = await ethers.deployContract("WhistleblowerRegistry", [verifierAddr]);
    const registryAddr = await registry.getAddress();
    console.log("WhistleblowerRegistry:", registryAddr);

    // Save addresses for frontend
    // @ts-ignore
    const networkName = network.name ?? process.env.HARDHAT_NETWORK ?? "localhost";
    const frontendEnvPath = resolve(import.meta.dirname, "../frontend/.env.local");

    const managedKeys = new Set([
        "NEXT_PUBLIC_REGISTRY_ADDRESS",
        "NEXT_PUBLIC_VERIFIER_ADDRESS",
        "NEXT_PUBLIC_NETWORK_NAME",
    ]);

    const existingEnv = existsSync(frontendEnvPath)
        ? readFileSync(frontendEnvPath, "utf8")
        : "";
    const preservedLines = existingEnv
        .split(/\r?\n/)
        .filter((line) => {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith("#")) return false;
            const key = trimmed.split("=", 1)[0];
            return !managedKeys.has(key);
        });

    const envContent = `# Auto-generated by deploy script on ${new Date().toISOString()}
NEXT_PUBLIC_REGISTRY_ADDRESS=${registryAddr}
NEXT_PUBLIC_VERIFIER_ADDRESS=${verifierAddr}
NEXT_PUBLIC_NETWORK_NAME=${networkName}
${preservedLines.length ? `\n${preservedLines.join("\n")}\n` : ""}`;

    mkdirSync(resolve(frontendEnvPath, ".."), { recursive: true });
    writeFileSync(frontendEnvPath, envContent);

    console.log(`\n✓ Addresses saved to frontend/.env.local`);
    console.log(`\nFor local development, frontend should auto-detect localhost.`);
    console.log(`For testnet (${networkName}), update frontend/.env.local manually if needed.`);
}

main().catch(console.error);
