import { network } from "hardhat";
import { writeFileSync, mkdirSync } from "fs";
import { resolve } from "path";

const { ethers } = await network.connect();

async function main() {
    const verifier = await ethers.deployContract("Groth16Verifier");
    const verifierAddr = await verifier.getAddress();
    console.log("Groth16Verifier:", verifierAddr);

    const registry = await ethers.deployContract("WhistleblowerRegistry", [verifierAddr]);
    const registryAddr = await registry.getAddress();
    console.log("WhistleblowerRegistry:", registryAddr);

    // Save addresses for frontend
    const networkName = network.name;
    const frontendEnvPath = resolve(import.meta.dirname, "../frontend/.env.local");

    const envContent = `# Auto-generated by deploy script on ${new Date().toISOString()}
NEXT_PUBLIC_REGISTRY_ADDRESS=${registryAddr}
NEXT_PUBLIC_VERIFIER_ADDRESS=${verifierAddr}
NEXT_PUBLIC_NETWORK_NAME=${networkName}
`;

    mkdirSync(resolve(frontendEnvPath, ".."), { recursive: true });
    writeFileSync(frontendEnvPath, envContent);

    console.log(`\n✓ Addresses saved to frontend/.env.local`);
    console.log(`\nFor local development, frontend should auto-detect localhost.`);
    console.log(`For testnet (${networkName}), update frontend/.env.local manually if needed.`);
}

main().catch(console.error);
